- name: Set up the Garden Lightshow host
  hosts: gardenpi
  roles:
    - role: archlinuxarm
      tags: [system]
    - role: flaky-network
      tags: [system]
    - role: lightshow
      tags: [app]
