
- name: Set up Timelapse NFS store
  hosts: mustela
  roles:
    - timelapse_store
  vars:
    timelapse_store: /data/pirrigator


- name: Set up the Pirrigator system
  hosts: pirrigator
  roles:
    - archlinuxarm
    - flaky-network
    - pirrigator
    - timelapse
  vars:
    nfs_mount_host: mustela
    nfs_mount_store: /data/pirrigator


- name: Set up the Garden Lightshow host
  hosts: gardenpi
  roles:
    - archlinuxarm
    - flaky-network
    - lightshow


- name: Set up the Window Controller host
  hosts: veluxpi
  roles:
    - archlinuxarm
    - velux


- name: Set up the test Raspberry Pi
  hosts: alarmpi
  roles:
    - timelapse
    - pirrigator
  vars:
    nfs_mount_remote: 192.168.0.3:/data/pirrigator

