
- name: Set up Timelapse NFS store
  hosts: mustela
  roles:
    - timelapse_store
  vars:
    timelapse_store: /data/pirrigator


- name: Set up the Timelapse Raspberry Pi
  hosts: pirrigator
  roles:
    - archlinuxarm
    - flaky-network
    - timelapse
  vars:
    nfs_mount_host: mustela
    nfs_mount_store: /data/pirrigator
