
- name: Set up Timelapse NFS store
  hosts: mustela
  roles:
    - role: timelapse_store
      tags: [app]
  vars:
    timelapse_store: /data/pirrigator


- name: Set up the Timelapse Raspberry Pi
  hosts: pirrigator
  roles:
    - role: archlinuxarm
      tags: [system]
    - role: flaky-network
      tags: [system]
    - role: timelapse
      tags: [app]
  vars:
    nfs_mount_host: mustela
    nfs_mount_store: /data/pirrigator
