---
# tasks file for archlinuxarm

- name: Enable SSH based sudo authorisation
  lineinfile:
    path: /etc/pam.d/sudo
    line: 'auth sufficient pam_ssh_agent_auth.so file=/etc/security/authorized_keys'
    insertbefore: '^auth\s+include\s+system-auth'
    state: present


- name: Update sudoers
  lineinfile:
    path: /etc/sudoers
    line: 'Defaults env_keep += "SSH_AUTH_SOCK"'
    insertafter: '^#\s*Defaults'
    state: present


- name: Install authorisation key for sudo
  copy:
    src: files/keys/id_rsa.pub
    dest: /etc/security/authorized_keys
    owner: root
    group: root
    mode: u=rw,g=r,o=r


- name: Remove Geo-IP based Pacman mirror
  replace:
    path: /etc/pacman.d/mirrorlist
    regexp: '^(Server\s*=\s*http://mirror\.archlinuxarm\.org/.*)$'
    replace: '# \1'


- name: Enable European Pacman mirrors
  replace:
    path: /etc/pacman.d/mirrorlist
    regexp: '^#\s*(Server\s*=\s*http://{{item}}\.mirror\.archlinuxarm\.org/.*)$'
    replace: '\1'
  loop:
    - dk
    - fr
    - de
    - de3
    - nl


- name: Disable DNSSec
  register: dnssec
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#DNSSEC='
    line: DNSSEC=false


- name: Restart systemd-resolved
  when: dnssec.changed
  systemd:
    name: systemd-resolved
    state: restarted


- name: Update system
  pacman:
    update_cache: yes
    upgrade: yes


- name: Install packages
  pacman:
    name:
      - file
      - base-devel
      - git
      - python-pip
      - vim
    state: present
