---
# tasks file for archlinuxarm

- name: Remove Geo-IP based Pacman mirror
  replace:
    path: /etc/pacman.d/mirrorlist
    regexp: '^(Server\s*=\s*http://mirror\.archlinuxarm\.org/.*)$'
    replace: '# \1'


- name: Enable European Pacman mirrors
  replace:
    path: /etc/pacman.d/mirrorlist
    regexp: '^#\s*(Server\s*=\s*http://{{item}}\.mirror\.archlinuxarm\.org/.*)$'
    replace: '\1'
  loop:
    - dk
    - fr
    - de
    - de3
    - nl


- name: Disable DNSSec
  register: dnssec
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#DNSSEC='
    line: DNSSEC=false


- name: Restart systemd-resolved
  when: dnssec.changed
  systemd:
    name: systemd-resolved
    state: restarted


- name: Update system
  pacman:
    update_cache: yes
    upgrade: yes


- name: Install packages
  pacman:
    name:
      - file
      - base-devel
      - git
      - python-pip
      - vim
    state: present
