---
# tasks file for archlinuxarm


- name: Disable DNSSec
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#DNSSEC='
    line: DNSSEC=false
  notify: restart-systemd-resolved


- name: Update system
  pacman:
    update_cache: yes
    upgrade: yes


- name: Install packages
  pacman:
    name:
      - file
      - base-devel
      - git
      - python-pip
      - vim
    state: present


- name: Install GPIO reset script
  copy:
    src: files/scripts/reset-gpio.sh
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "0755"

