---
# tasks file for velux

- name: Install Python packages
  pip:
    name: AWSIoTPythonSDK,requests,RPi.GPIO


- name: Install Velux systemd service
  register: velux_systemd
  template:
    src: templates/systemd/velux.service
    dest: /lib/systemd/system/velux.service
    owner: root
    group: root


- name: Install Velux scripts
  copy:
    src: files/scripts/
    dest: "{{velux_install_dir}}"
    owner: root
    group: root


- name: Start Velux systemd se=rvice 
  when: velux_systemd.changed
  systemd:
    daemon-reload: yes
    name: velux.service
    state: started
    enabled: yes
