---
# tasks file for pirrigator

- name: Install packages
  pacman:
    name:
      - i2c-tools
      - lm_sensors
    state: present


- name: Enable I²C driver
  lineinfile:
    path: /etc/modules-load.d/raspberrypi.conf
    line: i2c-dev
    state: present
  notify: reboot


- name: Enable I²C BCM2708 driver
  lineinfile:
    path: /etc/modules-load.d/raspberrypi.conf
    line: i2c-bcm2708
    state: present
  notify: reboot


- name: Install Pirrigator binary
  copy:
    src: files/build/pirrigator
    dest: "{{pirrigator_executable}}"
    owner: root
    group: root
    mode: "0755"


- name: Create Pirrigator configuration directory
  file:
    path: "{{pirrigator_config_dir}}/"
    state: directory


- name: Install Pirrigator configuration
  copy:
    src: files/build/Settings.yaml
    dest: "{{pirrigator_config_dir}}/Settings.yaml"
    owner: root
    group: root
    mode: "0644"


- name: Install GPIO reset script
  copy:
    src: files/bin/reset-gpio.sh
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "0755"


- name: Install Pirrigator systemd unit
  register: systemd_pirrigator
  template:
    src: templates/systemd/pirrigator.service
    dest: /lib/systemd/system/pirrigator.service
    owner: root
    group: root


- name: Start Pirrigator service
  when: systemd_pirrigator.changed
  systemd:
    daemon-reload: yes
    name: pirrigator.service
    state: started
    enabled: yes


- name: Set Pirrigator host boot configuration
  copy:
    src: files/boot/config.txt
    dest: /boot/config.txt
    owner: root
    group: root
