---
# tasks file for pirrigator

- name: Install Pirrigator systemd unit
  template:
    src: templates/systemd/pirrigator.service
    dest: /lib/systemd/system/pirrigator.service
    owner: root
    group: root


- name: Start Pirrigator service
  systemd:
    daemon-reload: yes
    name: pirrigator.service
    state: started
    enabled: yes


- name: Set Pirrigator host boot configuration
  copy:
    src: files/boot/config.txt
    dest: /boot/config.txt
    owner: root
    group: root
