---
# tasks file for lightshow

- name: Install Lightshow systemd service
  template:
    src: templates/systemd/lightshow.service
    dest: /lib/systemd/system/lightshow.service
    owner: root
    group: root


- name: Install Lightshow Configuration
  copy:
    src: files/lib/
    dest: "{{lightshow_lib_dir}}"
    owner: root
    group: root
  notify: restart-lightshow


- name: Install Lightshow Binary
  copy:
    src: files/build/lightshow
    dest: "{{lightshow_bin_dir}}"
    mode: "0755"
  notify: restart-lightshow


- name: Set Lightshow host boot configuration
  copy:
    src: files/boot/config.txt
    dest: /boot/config.txt
    owner: root
    group: root
  notify: reboot    