---
# tasks file for lightshow

- name: Install Python packages
  pip:
    name: AWSIoTPythonSDK,requests,RPi.GPIO


- name: Install Lightshow systemd service
  register: lightshow_systemd
  template:
    src: templates/systemd/lightshow.service
    dest: /lib/systemd/system/lightshow.service
    owner: root
    group: root


- name: Install Lightshow scripts
  copy:
    src: files/scripts/
    dest: "{{lightshow_install_dir}}"
    owner: root
    group: root


- name: Start Lightshow systemd service
  when: lightshow_systemd.changed
  systemd:
    daemon-reload: yes
    name: lightshow.service
    state: started
    enabled: yes


- name: Set Lightshow host boot configuration
  copy:
    src: files/boot/config.txt
    dest: /boot/config.txt
    owner: root
    group: root
    